export const STOCKS_ACTION_TYPES = {
  FETCH_STOCKS_START: 'stocks/FETCH_STOCKS_START',
  FETCH_STOCKS_SUCCESS: 'stocks/FETCH_STOCKS_SUCCESS',
  FETCH_STOCKS_UPDATE_SUCCESS: 'stocks/FETCH_STOCKS_UPDATE_SUCCESS',
  FETCH_STOCKS_FAILED: 'stocks/FETCH_STOCKS_FAILED',
};
